[package]
name = "fmite-derive"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
description = "Derives for fmite: Variables and Enumeration"
license = "MIT OR Apache-2.0"
repository = "https://github.com/astra-laboratories/fmite"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }
